name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase
        run: |
          curl -X GET "https://uknovavxcfzljostuznk.supabase.co/rest/v1/lugares?select=id&limit=1" \
            -H "apikey: ${{ secrets.SUPABASE_API_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_API_KEY }}"
